name: mp3_player
description: A library for play mp3 file in ternimal, and it is based on mpg123
version: 0.1.1
homepage: https://alanalbert.github.io

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  # dio: ^3.0.9

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
